# Generated by Django 2.1.5 on 2019-01-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_govuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='govuser',
            old_name='gov',
            new_name='user',
        ),
    ]
