# Generated by Django 2.1.5 on 2019-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190128_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
