# Generated by Django 2.1.5 on 2019-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_govuser_is_supergov'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_num', models.PositiveIntegerField()),
                ('otp', models.PositiveIntegerField()),
                ('send_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
