# Generated by Django 2.1.5 on 2019-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='govuser',
            name='phone_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
