# Generated by Django 2.1.5 on 2019-01-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Booth Level Complaints', 'Booth Level Complaints'), ('Booth Capturing', 'Booth Capturing'), ('Bogus Voting', 'Bogus Voting'), ('Liquor Distribution', 'Liquor Distribution'), ('Money Distribution', 'Money Distribution'), ('Over Campaigning', 'Over Campaigning'), ('Obstruction to voters', 'Obstruction to voters'), ('No armed forces', 'No armed forces'), ('EVM Malfunctioning', 'EVM Malfunctioning')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, upload_to='files')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('user', 'choice')},
        ),
    ]
