# Generated by Django 2.1.5 on 2019-01-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='choice',
        ),
    ]
