# Generated by Django 2.1.5 on 2019-01-25 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_auto_20190125_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='choice',
            field=models.CharField(choices=[('Booth Level Complaints', 'Booth Level Complaints'), ('Booth Capturing', 'Booth Capturing'), ('Bogus Voting', 'Bogus Voting'), ('Liquor Distribution', 'Liquor Distribution'), ('Money Distribution', 'Money Distribution'), ('Over Campaigning', 'Over Campaigning'), ('Obstruction to voters', 'Obstruction to voters'), ('No armed forces', 'No armed forces'), ('EVM Malfunctioning', 'EVM Malfunctioning')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('user', 'choice')},
        ),
    ]
