# Generated by Django 2.1.5 on 2019-01-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20190125_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='choice',
            field=models.CharField(choices=[('Booth Capturing', 'Booth Capturing'), ('Bogus Voting', 'Bogus Voting'), ('Liquor Distribution', 'Liquor Distribution'), ('Money Distribution', 'Money Distribution'), ('Over Campaigning', 'Over Campaigning'), ('Obstruction to voters', 'Obstruction to voters'), ('No armed forces', 'No armed forces'), ('EVM Malfunctioning', 'EVM Malfunctioning')], max_length=50),
        ),
    ]
