# Generated by Django 2.1.5 on 2019-01-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20190125_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='file_upload1',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='file_upload2',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='file_upload3',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='file_upload4',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='file_upload5',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
