# Generated by Django 2.1.5 on 2019-01-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20190126_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='viewed_complaint',
            field=models.BooleanField(default=False),
        ),
    ]
