# Generated by Django 2.1.5 on 2019-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='choice',
            field=models.CharField(choices=[('Booth Capturing', 'Booth Capturing'), ('Bogus Voting', 'Bogus Voting'), ('Obstruction to Voters', 'Obstruction to Voters'), ('No Armed Forces', 'No Armed Forces'), ('EVM Malfunctioning', 'EVM Malfunctioning'), ('Liquor Distribution', 'Liquor Distribution'), ('Money Distribution', 'Money Distribution'), ('Over Campaigning', 'Over Campaigning')], max_length=50),
        ),
    ]
